language: cpp

sudo: false

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

env:
  global:
    secure: MW6tNPPUcb7rxTXb1XvOQA6VQfwZSKjbnlNuTj/z+WPGzas5tjUShLfF0BcknOP8IVyYWV14jTKn89SDhlZi3oYw8xVJxbmH049c4qab5/SMTV0wFjl85Kgmt1aIUTdtDHBNrfYDHpGUr80nuLFMq+kgkhflDOU50p22fZ0gtiNftFn6mvnqkoC9rZBUis0SXG3NqEDjdJKYtNRsjlN9UX4oKHW4qwiOrJULNbfJVSkSx9Wq/ZfIRAb4YOIQt5lL89ory5I6dnyMje32cikJH7jJ6JhYckvYrULLsvl7zgmjpw8zncKy95+HYg2huK84TvvhfajWzGbb1oIUFfqdd0bjxnD6AJlQ/Ybbs7RhSyJ/3306I0zXoOqr0EHVhVS4iy9FZOaBQkwykOhmZVs67c+9J0ONNT7eiX8wFue9NYLVFHNq7afOfggfuXv250j78tFqSH+ytomKYNzrvchbLa7VsC0IMtesYg6oTlEpik51FTJmuE8UjpzC27jAGhOiprmUSl0Zfnb+sd5UsTEBLLDv79V2CWHU2WCXksrLp597fkDUPJTBYCDv4OojDf7vwyR5GOwwDCmsCufx7bLVw8Wr4TXztw96Wshxq2TDDf4L43DreFx3frt8vkWqbHFHI0/1ssO8MBGn0/kRndZyXAtIgmQxtY7DRcdo0UcUw7k=

matrix:
  include:
    - env: PYGMO_BUILD_TYPE="osx_debug_pagmo_latest" PYTHON_VERSION="3.8"
      os: osx
      osx_image: xcode10.3
    - env: PYGMO_BUILD_TYPE="osx_debug_pagmo_head" PYTHON_VERSION="3.8"
      os: osx
      osx_image: xcode10.3
    - env: PYGMO_BUILD_TYPE="osx_debug_pagmo_latest" PYTHON_VERSION="3.7"
      os: osx
      osx_image: xcode10.3
    - env: PYGMO_BUILD_TYPE="osx_debug_pagmo_head" PYTHON_VERSION="3.7"
      os: osx
      osx_image: xcode10.3
    - env: PYGMO_BUILD_TYPE="osx_debug_pagmo_latest" PYTHON_VERSION="3.6"
      os: osx
      osx_image: xcode10.3
    - env: PYGMO_BUILD_TYPE="osx_debug_pagmo_head" PYTHON_VERSION="3.6"
      os: osx
      osx_image: xcode10.3
    - env: PYGMO_BUILD_TYPE="manylinux64Py38_head" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
      sudo: required
      services:
      - docker
    - env: PYGMO_BUILD_TYPE="manylinux64Py38_latest" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
      sudo: required
      services:
      - docker
    - env: PYGMO_BUILD_TYPE="manylinux64Py37_head" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
      sudo: required
      services:
      - docker
    - env: PYGMO_BUILD_TYPE="manylinux64Py37_latest" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
      sudo: required
      services:
      - docker
    - env: PYGMO_BUILD_TYPE="manylinux64Py36_head" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
      sudo: required
      services:
      - docker
    - env: PYGMO_BUILD_TYPE="manylinux64Py36_latest" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
      sudo: required
      services:
      - docker
script:  
    - if [[ "${PYGMO_BUILD_TYPE}" == osx* ]]; then bash tools/travis_osx.sh; fi
    - if [[ "${PYGMO_BUILD_TYPE}" == manylinux* ]]; then bash tools/travis_manylinux.sh; fi

notifications:
  email: false
