version: 2.1

jobs:
  bionic_gcc7_pagmo_head_38:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_pagmo_head_38.sh
  bionic_gcc7_pagmo_head_37:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_pagmo_head_37.sh
  bionic_gcc7_pagmo_head_39:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_pagmo_head_39.sh

workflows:
  version: 2.1
  all_builds:
    jobs:
    - bionic_gcc7_pagmo_head_38
    - bionic_gcc7_pagmo_head_37
    - bionic_gcc7_pagmo_head_39
