version: 2

jobs:
  cosmic_gcc8_pagmo_head:
    docker:
    - image: circleci/buildpack-deps:cosmic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_cosmic_gcc8_pagmo_head.sh

workflows:
  version: 2
  all_builds:
    jobs:
    - cosmic_gcc8_pagmo_head
