# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos-10_15-py310:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_macos-10.15-py310.sh
  macos-10_15-py38:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_macos-10.15-py38.sh
  macos-10_15-py39:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_macos-10.15-py39.sh
  windows-2019-py38:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: .\tools\gha_windows.ps1
        shell: powershell
  windows-2019-py39:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: .\tools\gha_windows.ps1
        shell: powershell
